# Generated by Django 5.1.5 on 2025-05-06 19:08

import django.db.models.deletion
import makeup_exam.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup_exam', '0002_delete_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResitExamAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Resit Announcement Title')),
                ('exam_datetime', models.DateTimeField(verbose_name='Exam Date and Time')),
                ('exam_place', models.CharField(max_length=200, verbose_name='Exam Place (e.g., Classroom A-101)')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional Information / Rules')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to=makeup_exam.models.resit_exam_announcement_file_path, verbose_name='Attach File (e.g., Exam Topics, Seating Plan)')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resit_exam_details', to='makeup_exam.course', verbose_name='Related Course')),
                ('posted_by', models.ForeignKey(limit_choices_to={'profile__role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resit Exam Announcement',
                'verbose_name_plural': 'Resit Exam Announcements',
                'ordering': ['-posted_at'],
            },
        ),
    ]
